server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Обслуживание фронта
    location / {
        try_files $uri /index.html;
    }

    # Проксирование всех API-запросов на внешний бэкенд
    location /api/ {
        proxy_pass http://92.242.60.110:8000/;   # Внешний IP бэка, слеш обязателен
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
